### ISSUE TITLE
Sample app crashes when browsing the view hierarchy in Stetho

### ISSUE THREAD

**Issue by jbarr21** [facebook/litho#102]
- [X] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
Using an Nexus 6P on Android 7.1.2:
1. `./gradlew :sample:installDebug`
2. Open the sample app, navigate to the Lithography list
3. Connect to Stetho
4. Click the search button in Stetho view hierachy
5. Tap on the first image in the list

## Expected Behavior
No crash

## Link to Code
```
04-19 15:26:47.672 30649-30649/com.facebook.samples.litho E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.facebook.samples.litho, PID: 30649
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/litho/annotations/Prop;
        at com.facebook.litho.ComponentStethoNodeDescriptor.onGetStyles(ComponentStethoNodeDescriptor.java:193)
        at com.facebook.litho.ComponentStethoNodeDescriptor.onGetStyles(ComponentStethoNodeDescriptor.java:26)
        at com.facebook.stetho.inspector.elements.AbstractChainedDescriptor.getStyles(AbstractChainedDescriptor.java:154)
        at com.facebook.stetho.inspector.elements.Document.getElementStyles(Document.java:153)
        at com.facebook.stetho.inspector.protocol.module.CSS$2$1.store(CSS.java:144)
        at com.facebook.litho.ComponentStethoNodeDescriptor.onGetStyleRuleNames(ComponentStethoNodeDescriptor.java:152)
        at com.facebook.litho.ComponentStethoNodeDescriptor.onGetStyleRuleNames(ComponentStethoNodeDescriptor.java:26)
        at com.facebook.stetho.inspector.elements.AbstractChainedDescriptor.getStyleRuleNames(AbstractChainedDescriptor.java:145)
        at com.facebook.stetho.inspector.elements.Document.getElementStyleRuleNames(Document.java:147)
        at com.facebook.stetho.inspector.protocol.module.CSS$2.run(CSS.java:118)
        at com.facebook.stetho.common.android.HandlerUtil$2.onRun(HandlerUtil.java:90)
        at com.facebook.stetho.common.android.HandlerUtil$2.onRun(HandlerUtil.java:87)
        at com.facebook.stetho.common.android.HandlerUtil$WaitableRunnable.run(HandlerUtil.java:109)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6121)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.litho.annotations.Prop" on path: DexPathList[[zip file "/data/app/com.facebook.samples.litho-1/base.apk"],nativeLibraryDirectories=[/data/app/com.facebook.samples.litho-1/lib/arm64, /system/fake-libs64, /data/app/com.facebook.samples.litho-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.facebook.litho.ComponentStethoNodeDescriptor.onGetStyles(ComponentStethoNodeDescriptor.java:193) 
        at com.facebook.litho.ComponentStethoNodeDescriptor.onGetStyles(ComponentStethoNodeDescriptor.java:26) 
        at com.facebook.stetho.inspector.elements.AbstractChainedDescriptor.getStyles(AbstractChainedDescriptor.java:154) 
        at com.facebook.stetho.inspector.elements.Document.getElementStyles(Document.java:153) 
        at com.facebook.stetho.inspector.protocol.module.CSS$2$1.store(CSS.java:144) 
        at com.facebook.litho.ComponentStethoNodeDescriptor.onGetStyleRuleNames(ComponentStethoNodeDescriptor.java:152) 
        at com.facebook.litho.ComponentStethoNodeDescriptor.onGetStyleRuleNames(ComponentStethoNodeDescriptor.java:26) 
        at com.facebook.stetho.inspector.elements.AbstractChainedDescriptor.getStyleRuleNames(AbstractChainedDescriptor.java:145) 
        at com.facebook.stetho.inspector.elements.Document.getElementStyleRuleNames(Document.java:147) 
        at com.facebook.stetho.inspector.protocol.module.CSS$2.run(CSS.java:118) 
        at com.facebook.stetho.common.android.HandlerUtil$2.onRun(HandlerUtil.java:90) 
        at com.facebook.stetho.common.android.HandlerUtil$2.onRun(HandlerUtil.java:87) 
        at com.facebook.stetho.common.android.HandlerUtil$WaitableRunnable.run(HandlerUtil.java:109) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6121) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
```

**Comment by IanChilds** [comment]
Hi James, thanks for the report. It should now be fixed by https://github.com/facebook/litho/commit/0eb3f21b5d4d39c42913dae0e2608383176f16e4.
