### ISSUE TITLE
I use Huawei mobile phones,Android  4.2.2and 7.0 are crash

### ISSUE THREAD

**Issue by doublechina** [facebook/litho#128]
I use Huawei mobile phones,Android  4.2.2and 7.0 are crash

build.gradle 
` // Litho
    compile 'com.facebook.litho:litho-core:0.2.0'
    compile 'com.facebook.litho:litho-widget:0.2.0'
    provided 'com.facebook.litho:litho-annotations:0.2.0'
    annotationProcessor 'com.facebook.litho:litho-processor:0.2.0'
    // SoLoader
    compile 'com.facebook.soloader:soloader:0.2.0'
    // Optional
    // For debugging
    debugCompile 'com.facebook.litho:litho-stetho:0.2.0'
    // For integration with Fresco
    compile 'com.facebook.litho:litho-fresco:0.2.0'
    // For testing
    testCompile 'com.facebook.litho:litho-testing:0.2.0'`

Activity:
` final ComponentContext c = new ComponentContext(this);
        final LithoView lithoView = LithoView.create(
                this /* context */,
                Text.create(c)
                        .text("Hello, World!")
                        .textSizeDip(50)
                        .build());
        setContentView(lithoView);`

Application:
`public class MyApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        SoLoader.init(this, false);
    }
}`

AndroidManifest.xml：
`application android:name=".MyApplication" `

I use Meizu Mx4 pro is normal ,Android version 5.1

**Comment by IanChilds** [comment]
Hi. Please can you use the template for your issue: https://github.com/facebook/litho/blob/master/CONTRIBUTING.md#issues
Unfortunately it will not be possible to debug this without the logcat of the crash.

**Comment by doublechina** [comment]
This is my debug crash log:
```
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho W/dalvikvm: Pending exception is:
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm: java.lang.NoClassDefFoundError: com/facebook/jni/Countable
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at java.lang.Runtime.nativeLoad(Native Method)
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at java.lang.Runtime.load(Runtime.java:339)
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at java.lang.System.load(System.java:500)
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.facebook.soloader.SoLoader$1.load(SoLoader.java:279)
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:69)
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:40)
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:427)
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:63)
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:40)
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:427)
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:367)
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:332)
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.facebook.yoga.YogaConfig.<clinit>(YogaConfig.java:19)
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.facebook.litho.ComponentsPools.acquireYogaNode(ComponentsPools.java:172)
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.facebook.litho.ComponentsPools.acquireInternalNode(ComponentsPools.java:190)
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.facebook.litho.ComponentContext.newLayoutBuilder(ComponentContext.java:250)
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.facebook.litho.Column.create(Column.java:25)
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.facebook.litho.Column.create(Column.java:29)
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.facebook.litho.ComponentLifecycle.onCreateLayout(ComponentLifecycle.java:324)
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:229)
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.facebook.litho.LayoutState.createTree(LayoutState.java:1141)
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.facebook.litho.LayoutState.createAndMeasureTreeForComponent(LayoutState.java:1312)
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.facebook.litho.LayoutState.calculate(LayoutState.java:907)
04-25 08:59:15.113 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.facebook.litho.ComponentTree.calculateLayoutState(ComponentTree.java:1241)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.facebook.litho.ComponentTree.measure(ComponentTree.java:526)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.facebook.litho.LithoView.onMeasure(LithoView.java:211)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at android.view.View.measure(View.java:15898)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5085)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:337)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at android.view.View.measure(View.java:15898)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:943)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:624)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at android.view.View.measure(View.java:15898)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5085)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:337)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2233)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at android.view.View.measure(View.java:15898)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2273)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1333)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1528)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1223)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5062)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at android.view.Choreographer.doCallbacks(Choreographer.java:579)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at android.view.Choreographer.doFrame(Choreographer.java:548)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at android.os.Handler.handleCallback(Handler.java:800)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at android.os.Handler.dispatchMessage(Handler.java:100)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at android.os.Looper.loop(Looper.java:194)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at android.app.ActivityThread.main(ActivityThread.java:5468)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at java.lang.reflect.Method.invokeNative(Native Method)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at java.lang.reflect.Method.invoke(Method.java:525)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:936)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
04-25 08:59:15.114 6888-6888/com.doublechina.autolitho I/dalvikvm:     at dalvik.system.NativeStart.main(Native Method)

```

**Comment by IanChilds** [comment]
This is the same as #108
