### ISSUE TITLE
Couldn't install sample app

### ISSUE THREAD

**Issue by lenguyenthanh** [facebook/litho#154]
- [ x ] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
* Run `./gradlew :sample:installDebug` It failed with 
```
litho/litho-core/src/main/java/com/facebook/litho/ComponentsPools.java
Error:(175, 20) error: cannot find symbol method setUseLegacyStretchBehaviour(boolean)
````

* Run `buck install -r sample` it was installed but crashed immediately. Here is stacktracke:
```
AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.facebook.samples.litho, PID: 7182
                                                 java.lang.NoSuchMethodError: No virtual method setUseLegacyStretchBehaviour(Z)V in class Lcom/facebook/yoga/YogaConfig; or its super classes (declaration of 'com.facebook.yoga.YogaConfig' appears in /data/app/com.facebook.samples.litho-1/base.apk)
                                                     at com.facebook.litho.ComponentsPools.acquireYogaNode(ComponentsPools.java:175)
                                                     at com.facebook.litho.ComponentsPools.acquireInternalNode(ComponentsPools.java:191)
                                                     at com.facebook.litho.ComponentContext.newLayoutBuilder(ComponentContext.java:250)
                                                     at com.facebook.litho.Column.create(Column.java:25)
                                                     at com.facebook.litho.Column.create(Column.java:29)
                                                     at com.facebook.litho.ComponentLifecycle.onCreateLayout(ComponentLifecycle.java:324)
                                                     at com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:229)
                                                     at com.facebook.litho.ComponentContext.newLayoutBuilder(ComponentContext.java:261)
                                                     at com.facebook.litho.Layout.create(Layout.java:37)
                                                     at com.facebook.litho.Component$Builder.withLayout(Component.java:113)
                                                     at com.facebook.samples.litho.DemoListComponentSpec.onCreateLayout(DemoListComponentSpec.java:41)
                                                     at com.facebook.samples.litho.DemoListComponent.onCreateLayout(DemoListComponent.java:29)
                                                     at com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:229)
                                                     at com.facebook.litho.LayoutState.createTree(LayoutState.java:1158)
                                                     at com.facebook.litho.LayoutState.createAndMeasureTreeForComponent(LayoutState.java:1327)
                                                     at com.facebook.litho.LayoutState.calculate(LayoutState.java:908)
                                                     at com.facebook.litho.ComponentTree.calculateLayoutState(ComponentTree.java:1226)
                                                     at com.facebook.litho.ComponentTree.measure(ComponentTree.java:537)
                                                     at com.facebook.litho.LithoView.onMeasure(LithoView.java:205)
                                                     at android.view.View.measure(View.java:18804)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                     at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                     at android.view.View.measure(View.java:18804)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                     at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:393)
                                                     at android.view.View.measure(View.java:18804)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                     at android.view.View.measure(View.java:18804)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                     at android.view.View.measure(View.java:18804)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                     at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                     at android.view.View.measure(View.java:18804)
                                                     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2112)
                                                     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1228)
                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1464)
                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                     at android.os.Handler.handleCallback(Handler.java:746)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.r
```

## Expected Behavior
App is installed success and works well.

## Link to Code
There is no code needed. All I got newest code at this time.

**Comment by passy** [comment]
Circle CI Is red for the same reason.

cc @Em

**Comment by newfivefour** [comment]
Just cloned and had the same issue.

**Comment by passy** [comment]
This is now fixed on master. Sorry about that!

**Comment by auhah** [comment]
I have a similar problem
The only difference is i got success when to run `./gradlew :sample:installDebug`

All this happened at 8d97c1f2e2174990482210680c60a3bcf67192c8

**Comment by passy** [comment]
@auhah Could you open a new issue and post the error message you're seeing?
