### ISSUE TITLE
StackOverflowError when using touchExpansion

### ISSUE THREAD

**Issue by sushshring** [facebook/litho#198]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
I need to add a recyclerView in the toolbar of my activity, and I cannot call setContentView() with the LithoView. Currently, I'm trying to add the generated LithoView as a sub child to an existing LinearLayout. However, this sends the renderer into an infinite number of recursive calls and overflows the stack.

## Expected Behavior
I expect the LinearLayout to add the LithoView as a child.

## Link to Code

```java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        LinearLayout layout = toolbar.findViewById(R.id.tagLinearLayout);
        final ComponentContext context = new ComponentContext(this);
        RecyclerBinder binder = new RecyclerBinder(context, new LinearLayoutInfo(this,
            LinearLayout.HORIZONTAL, true));
        final Component component = Recycler.create(context)
                .binder(binder)
                .build();
        layout.addView(LithoView.create(context, component));
    }
```

**Comment by passy** [comment]
@sushshring Could you post the stacktrace that you're seeing for the recursive loop?

**Comment by sushshring** [comment]
Adding stack trace. The error happens as soon as I touch the element.


```
06-13 15:28:57.395 1396-1396/me.sushshring.hotspot E/InputEventReceiver: Exception dispatching input event.
06-13 15:28:57.405 1396-1396/me.sushshring.hotspot E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
06-13 15:28:57.625 1396-1412/me.sushshring.hotspot I/art: Background sticky concurrent mark sweep GC freed 16551(1257KB) AllocSpace objects, 7(472KB) LOS objects, 0% free, 15MB/15MB, paused 1.068ms total 188.385ms
06-13 15:28:57.885 1396-1396/me.sushshring.hotspot E/MessageQueue-JNI: java.lang.StackOverflowError: stack size 8MB
                                                                           at com.facebook.litho.ComponentHost.onInterceptTouchEvent(ComponentHost.java:506)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1965)
                                                                           at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDelegate.java:207)
                                                                           at com.facebook.litho.TouchExpansionDelegate.onTouchEvent(TouchExpansionDelegate.java:93)
                                                                           at android.view.View.onTouchEvent(View.java:9439)
                                                                           at com.facebook.litho.ComponentHost.onTouchEvent(ComponentHost.java:697)
                                                                           at android.view.View.dispatchTouchEvent(View.java:8481)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2103)
                                                                           at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDelegate.java:207)
                                                                           at com.facebook.litho.TouchExpansionDelegate.onTouchEvent(TouchExpansionDelegate.java:93)
                                                                           at android.view.View.onTouchEvent(View.java:9439)
                                                                           at com.facebook.litho.ComponentHost.onTouchEvent(ComponentHost.java:697)
                                                                           at android.view.View.dispatchTouchEvent(View.java:8481)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2103)
                                                                           at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDelegate.java:207)
                                                                           at com.facebook.litho.TouchExpansionDelegate.onTouchEvent(TouchExpansionDelegate.java:93)
                                                                           at android.view.View.onTouchEvent(View.java:9439)
                                                                           at com.facebook.litho.ComponentHost.onTouchEvent(ComponentHost.java:697)
                                                                           at android.view.View.dispatchTouchEvent(View.java:8481)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2103)
                                                                           at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDelegate.java:207)
                                                                           at com.facebook.litho.TouchExpansionDelegate.onTouchEvent(TouchExpansionDelegate.java:93)
                                                                           at android.view.View.onTouchEvent(View.java:9439)
                                                                           at com.facebook.litho.ComponentHost.onTouchEvent(ComponentHost.java:697)
                                                                           at android.view.View.dispatchTouchEvent(View.java:8481)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2103)
                                                                           at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDelegate.java:207)
                                                                           at com.facebook.litho.TouchExpansionDelegate.onTouchEvent(TouchExpansionDelegate.java:93)
                                                                           at android.view.View.onTouchEvent(View.java:9439)
                                                                           at com.facebook.litho.ComponentHost.onTouchEvent(ComponentHost.java:697)
                                                                           at android.view.View.dispatchTouchEvent(View.java:8481)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2103)
                                                                           at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDelegate.java:207)
                                                                           at com.facebook.litho.TouchExpansionDelegate.onTouchEvent(TouchExpansionDelegate.java:93)
                                                                           at android.view.View.onTouchEvent(View.java:9439)
                                                                           at com.facebook.litho.ComponentHost.onTouchEvent(ComponentHost.java:697)
                                                                           at android.view.View.dispatchTouchEvent(View.java:8481)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2103)
                                                                           at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDelegate.java:207)
                                                                           at com.facebook.litho.TouchExpansionDelegate.onTouchEvent(TouchExpansionDelegate.java:93)
                                                                           at android.view.View.onTouchEvent(View.java:9439)
                                                                           at com.facebook.litho.ComponentHost.onTouchEvent(ComponentHost.java:697)
                                                                           at android.view.View.dispatchTouchEvent(View.java:8481)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2103)
                                                                           at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDelegate.java:207)
                                                                       	at com.facebook.litho.TouchExpansionDelegate.on
06-13 15:28:57.885 1396-1396/me.sushshring.hotspot D/AndroidRuntime: Shutting down VM
06-13 15:28:58.106 1396-1396/me.sushshring.hotspot E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: me.sushshring.hotspot, PID: 1396
                                                                     java.lang.StackOverflowError: stack size 8MB
                                                                         at com.facebook.litho.ComponentHost.onInterceptTouchEvent(ComponentHost.java:506)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1965)
                                                                         at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDelegate.java:207)
                                                                         at com.facebook.litho.TouchExpansionDelegate.onTouchEvent(TouchExpansionDelegate.java:93)
                                                                         at android.view.View.onTouchEvent(View.java:9439)
                                                                         at com.facebook.litho.ComponentHost.onTouchEvent(ComponentHost.java:697)
                                                                         at android.view.View.dispatchTouchEvent(View.java:8481)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2103)
                                                                         at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDelegate.java:207)
                                                                         at com.facebook.litho.TouchExpansionDelegate.onTouchEvent(TouchExpansionDelegate.java:93)
                                                                         at android.view.View.onTouchEvent(View.java:9439)
                                                                         at com.facebook.litho.ComponentHost.onTouchEvent(ComponentHost.java:697)
                                                                         at android.view.View.dispatchTouchEvent(View.java:8481)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2103)
                                                                         at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDelegate.java:207)
                                                                         at com.facebook.litho.TouchExpansionDelegate.onTouchEvent(TouchExpansionDelegate.java:93)
                                                                         at android.view.View.onTouchEvent(View.java:9439)
                                                                         at com.facebook.litho.ComponentHost.onTouchEvent(ComponentHost.java:697)
                                                                         at android.view.View.dispatchTouchEvent(View.java:8481)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2103)
                                                                         at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDelegate.java:207)
                                                                         at com.facebook.litho.TouchExpansionDelegate.onTouchEvent(TouchExpansionDelegate.java:93)
                                                                         at android.view.View.onTouchEvent(View.java:9439)
                                                                         at com.facebook.litho.ComponentHost.onTouchEvent(ComponentHost.java:697)
                                                                         at android.view.View.dispatchTouchEvent(View.java:8481)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2103)
                                                                         at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDelegate.java:207)
                                                                         at com.facebook.litho.TouchExpansionDelegate.onTouchEvent(TouchExpansionDelegate.java:93)
                                                                         at android.view.View.onTouchEvent(View.java:9439)
                                                                         at com.facebook.litho.ComponentHost.onTouchEvent(ComponentHost.java:697)
                                                                         at android.view.View.dispatchTouchEvent(View.java:8481)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2103)
                                                                         at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDelegate.java:207)
                                                                         at com.facebook.litho.TouchExpansionDelegate.onTouchEvent(TouchExpansionDelegate.java:93)
                                                                         at android.view.View.onTouchEvent(View.java:9439)
                                                                         at com.facebook.litho.ComponentHost.onTouchEvent(ComponentHost.java:697)
                                                                         at android.view.View.dispatchTouchEvent(View.java:8481)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2103)
                                                                         at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDelegate.java:207)
                                                                         at com.facebook.litho.TouchExpansionDelegate.onTouchEvent(TouchExpansionDelegate.java:93)
                                                                         at android.view.View.onTouchEvent(View.java:9439)
                                                                         at com.facebook.litho.ComponentHost.onTouchEvent(ComponentHost.java:697)
                                                                         at android.view.View.dispatchTouchEvent(View.java:8481)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2103)
                                                                     	at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDeleg
06-13 15:28:58.306 1396-1396/me.sushshring.hotspot D/Error: ERR: exClass=java.lang.StackOverflowError
06-13 15:28:58.306 1396-1396/me.sushshring.hotspot D/Error: ERR: exMsg=stack size 8MB
06-13 15:28:58.306 1396-1396/me.sushshring.hotspot D/Error: ERR: file=ComponentHost.java
06-13 15:28:58.306 1396-1396/me.sushshring.hotspot D/Error: ERR: class=com.facebook.litho.ComponentHost
06-13 15:28:58.306 1396-1396/me.sushshring.hotspot D/Error: ERR: method=onInterceptTouchEvent line=506
06-13 15:28:58.336 1396-1396/me.sushshring.hotspot D/Error: ERR: stack=java.lang.StackOverflowError: stack size 8MB
                                                                at com.facebook.litho.ComponentHost.onInterceptTouchEvent(ComponentHost.java:506)
                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1965)
                                                                at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDelegate.java:207)
                                                                at com.facebook.litho.TouchExpansionDelegate.onTouchEvent(TouchExpansionDelegate.java:93)
                                                                at android.view.View.onTouchEvent(View.java:9439)
                                                                at com.facebook.litho.ComponentHost.onTouchEvent(ComponentHost.java:697)
                                                                at android.view.View.dispatchTouchEvent(View.java:8481)
                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2103)
                                                                at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDelegate.java:207)
                                                                at com.facebook.litho.TouchExpansionDelegate.onTouchEvent(TouchExpansionDelegate.java:93)
                                                                at android.view.View.onTouchEvent(View.java:9439)
                                                                at com.facebook.litho.ComponentHost.onTouchEvent(ComponentHost.java:697)
                                                                at android.view.View.dispatchTouchEvent(View.java:8481)
                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2103)
                                                                at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDelegate.java:207)
                                                                at com.facebook.litho.TouchExpansionDelegate.onTouchEvent(TouchExpansionDelegate.java:93)
                                                                at android.view.View.onTouchEvent(View.java:9439)
                                                                at com.facebook.litho.ComponentHost.onTouchEvent(ComponentHost.java:697)
                                                                at android.view.View.dispatchTouchEvent(View.java:8481)
                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2103)
                                                                at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDelegate.java:207)
                                                                at com.facebook.litho.TouchExpansionDelegate.onTouchEvent(TouchExpansionDelegate.java:93)
                                                                at android.view.View.onTouchEvent(View.java:9439)
                                                                at com.facebook.litho.ComponentHost.onTouchEvent(ComponentHost.java:697)
                                                                at android.view.View.dispatchTouchEvent(View.java:8481)
                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2103)
                                                                at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDelegate.java:207)
                                                                at com.facebook.litho.TouchExpansionDelegate.onTouchEvent(TouchExpansionDelegate.java:93)
                                                                at android.view.View.onTouchEvent(View.java:9439)
                                                                at com.facebook.litho.ComponentHost.onTouchEvent(ComponentHost.java:697)
                                                                at android.view.View.dispatchTouchEvent(View.java:8481)
                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2103)
                                                                at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDelegate.java:207)
                                                                at com.facebook.litho.TouchExpansionDelegate.onTouchEvent(TouchExpansionDelegate.java:93)
                                                                at android.view.View.onTouchEvent(View.java:9439)
                                                                at com.facebook.litho.ComponentHost.onTouchEvent(ComponentHost.java:697)
                                                                at android.view.View.dispatchTouchEvent(View.java:8481)
                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2103)
                                                                at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDelegate.java:207)
                                                                at com.facebook.litho.TouchExpansionDelegate.onTouchEvent(TouchExpansionDelegate.java:93)
                                                                at android.view.View.onTouchEvent(View.java:9439)
                                                                at com.facebook.litho.ComponentHost.onTouchEvent(ComponentHost.java:697)
                                                                at android.view.View.dispatchTouchEvent(View.java:8481)
                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2103)
                                                                at com.facebook.litho.TouchExpansionDelegate$InnerTouchDelegate.onTouchEvent(TouchExpansionDelegate.java:207)
                                                            	at com.facebook.litho.TouchExpansionDelegate.on
06-13 15:28:58.336 1396-1396/me.sushshring.hotspot E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
06-13 15:28:58.336 1396-1396/me.sushshring.hotspot D/Error: ERR: TOTAL BYTES WRITTEN: 2390992
06-13 15:28:58.346 1396-1396/me.sushshring.hotspot E/AndroidRuntime: Error reporting crash
                                                                     android.os.TransactionTooLargeException
                                                                         at android.os.BinderProxy.transactNative(Native Method)
                                                                         at android.os.BinderProxy.transact(Binder.java:519)
                                                                         at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4217)
                                                                         at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:101)
                                                                         at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                         at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
```

**Comment by sushshring** [comment]
It seems I found the root cause of this. When touched, it did not seem to like the touchExpansion option at all. I don't understand why that is the issue, but once I got rid of that it renders just fine now.

**Comment by pasqualeanatriello** [comment]
@muraziz This seems like a bug in our touch expansion handling?

**Comment by vinc3m1** [comment]
Just FYI we're also seeing this stackoverflow when using Touch Expansion. Haven't had time to dig in and investigate yet but if you all have any info let us know!

**Comment by vinc3m1** [comment]
Can we rename this to something more relevant so it's easier to find? Like "StackOverflowError when using touchExpansion"?

**Comment by vinc3m1** [comment]
I was able to create a repro case, this seems to only happen when setting touchexpansion on the root element of a tree: https://github.com/vinc3m1/litho/commit/7e1b97da50fbc7622f36a35255672ddaabd8ace5

**Comment by yuntao** [comment]
I work with @vinc3m1 and did some investigation into this issue. 

This touch expansion related StackOverflowError (SOE) can be reproduced at both Litho layer and plain Android view layer. When touch expansion is set on any root Litho component, this logic propagates down to Android view layer and triggers a programmatically possible infinite loop condition in TouchDelegates and causes the SOE.

At Litho layer, the SOE can be triggered by setting touchExpansionDip and clickHandler on any root component. For example, both layout specs below produce the SOE when set as the root component to a LithoView:

```
@LayoutSpec
public class ColumnItemSpec {
  @OnCreateLayout
  static Component onCreateLayout(ComponentContext c) {
    return Column.create(c)
        .touchExpansionDip(ALL, 24)
        .clickHandler(ColumnItem.onClick(c))
        .build();
  }
  @OnEvent(ClickEvent.class)
  static void onClick(ComponentContext c, @FromEvent View view) {
  }
}
```
```
@LayoutSpec
public class TextItemSpec {
  @OnCreateLayout
  static Component onCreateLayout(ComponentContext c) {
    return Text.create(c)
        .text("Hello world")
        .touchExpansionDip(ALL, 24)
        .clickHandler(TextItem.onClick(c))
        .build();
  }
  @OnEvent(ClickEvent.class)
  static void onClick(ComponentContext c, @FromEvent View view) {
  }
}
```

At plain Android view layer, touch expansion is achieved by using a TouchDelegate in between a parent view group and a child view. It is programmatically possible to set a view's TouchDelegate to delegate to itself, as seen below. This causes an infinite loop of forwarding touch event to the view itself and thus the SOE.

```
View anyView = findViewById(R.id.any_view);
anyView.post(new Runnable() {
    @Override
    public void run() {
        Rect expandRect = new Rect();
        anyView.getHitRect(expandRect);
        expandRect.left -= 100;
        expandRect.top -= 100;
        expandRect.right += 100;
        expandRect.bottom += 100;
        anyView.setTouchDelegate(new TouchDelegate(expandRect, anyView));
        // Correct way is to set touch expansion on containing child view:
        // anyView.setTouchDelegate(new TouchDelegate(expandRect, childView));
    }
});
```

#### Suggestions on what could be done as fixes:

1. Update Litho docs on [touch expansion](https://fblitho.com/docs/events-touch-handling#touch-area-expansion) to indicate that touch expansion should not be set on the root component and will not work. If touch expansion is desired on the root LithoView, then android.view.TouchDelegate should be used instead and the parent view group is also needed.

2. Apply fix to [ComponentHost](https://github.com/facebook/litho/blob/ed625544714abc078a89d131688e5819c08abca9/litho-core/src/main/java/com/facebook/litho/ComponentHost.java#L300) class where we handle touch expansion to skip when the touch expansion been set on a LithoView itself:

```
void maybeRegisterTouchExpansion(int index, MountItem mountItem) {  
    if (this == MountItem.getContent()) {
        return;
    }
    ...
}

void maybeUnregisterTouchExpansion(int index, MountItem mountItem) {
    if (this == MountItem.getContent()) {
        return;
    }
    ...
}
```

**Comment by vinc3m1** [comment]
> did some investigation into this issue.

just to be clear @yuntao basically did *all* the investigation...

**Comment by sushshring** [comment]
Thank you @vinc3m1 @yuntao for your amazing work!

**Comment by muraziz** [comment]
Thanks for fixing this! @yuntao @vinc3m1
