### ISSUE TITLE
The following props are not marked as optional and were not supplied: [controller]

### ISSUE THREAD

**Issue by hanhailong** [facebook/litho#212]
java.lang.IllegalStateException: The following props are not marked as optional and were not supplied: [controller]
                                                                       at com.facebook.litho.Component$Builder.checkArgs(Component.java:98)
                                                                       at com.facebook.litho.fresco.FrescoImage$Builder.build(FrescoImage.java:488)
                                                                       at com.facebook.litho.Component$Builder.withLayout(Component.java:113)
                                                                       at com.hhl.lithodemo.spec.ImageListItemSpec.onCreateLayout(ImageListItemSpec.java:33)
                                                                       at com.hhl.lithodemo.spec.ImageListItem.onCreateLayout(ImageListItem.java:36)
                                                                       at com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:232)
                                                                       at com.facebook.litho.LayoutState.createTree(LayoutState.java:1217)
                                                                       at com.facebook.litho.LayoutState.createAndMeasureTreeForComponent(LayoutState.java:1386)
                                                                       at com.facebook.litho.LayoutState.calculate(LayoutState.java:923)
                                                                       at com.facebook.litho.ComponentTree.calculateLayoutState(ComponentTree.java:1304)
                                                                       at com.facebook.litho.ComponentTree.calculateLayout(ComponentTree.java:1077)
                                                                       at com.facebook.litho.ComponentTree.setRootAndSizeSpecInternal(ComponentTree.java:1023)
                                                                       at com.facebook.litho.ComponentTree.setRootAndSizeSpec(ComponentTree.java:895)
                                                                       at com.facebook.litho.widget.ComponentTreeHolder.computeLayoutSync(ComponentTreeHolder.java:88)
                                                                       at com.facebook.litho.widget.RecyclerBinder.initRange(RecyclerBinder.java:695)
                                                                       at com.facebook.litho.widget.RecyclerBinder.measure(RecyclerBinder.java:591)
                                                                       at com.facebook.litho.widget.RecyclerBinder.setSize(RecyclerBinder.java:721)
                                                                       at com.facebook.litho.widget.RecyclerSpec.onBoundsDefined(RecyclerSpec.java:89)
                                                                       at com.facebook.litho.widget.Recycler.onBoundsDefined(Recycler.java:80)
                                                                       at com.facebook.litho.LayoutState.collectResults(LayoutState.java:583)
                                                                       at com.facebook.litho.LayoutState.calculate(LayoutState.java:975)
                                                                       at com.facebook.litho.ComponentTree.calculateLayoutState(ComponentTree.java:1304)
                                                                       at com.facebook.litho.ComponentTree.measure(ComponentTree.java:594)
                                                                       at com.facebook.litho.LithoView.onMeasure(LithoView.java:218)
                                                                       at android.view.View.measure(View.java:19740)
                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                       at android.view.View.measure(View.java:19740)
                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                       at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:391)
                                                                       at android.view.View.measure(View.java:19740)
                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                       at android.view.View.measure(View.java:19740)
                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                       at android.view.View.measure(View.java:19740)
                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:687)
                                                                       at android.view.View.measure(View.java:19740)
                                                                       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2316)
                                                                       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1403)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1652)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1291)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6362)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:685)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
07-11 15:23:28.297 32224-32224/com.hhl.lithodemo E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:754)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:160)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6199)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)

the code is as follows:

Row.create(cc)
                .backgroundColor(Color.WHITE)
                .child(FrescoImage.create(cc)
                        .actualImageScaleType(ScalingUtils.ScaleType.CENTER_CROP)
                        .withLayout()
                        .widthDip(100)
                        .heightDip(100)
                )

**Comment by passy** [comment]
You need to specify a `DraweeController`. You can see an example use here: https://github.com/facebook/litho/blob/94cb400c90fd4e09430c42584693b29725e2dd8c/sample/src/main/java/com/facebook/samples/litho/lithography/SingleImageComponentSpec.java#L31
