### ISSUE TITLE
sample code UnsatisfiedLinkError error

### ISSUE THREAD

**Issue by zeng1990java** [facebook/litho#258]
Process: com.facebook.samples.litho, PID: 28469
                                                   java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.facebook.samples.litho/lib-main/libfb.so" is 64-bit instead of 32-bit
                                                       at java.lang.Runtime.load(Runtime.java:331)
                                                       at java.lang.System.load(System.java:981)
                                                       at com.facebook.soloader.SoLoader$1.load(SoLoader.java:279)
                                                       at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:69)
                                                       at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:40)
                                                       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:427)
                                                       at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:63)
                                                       at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:40)
                                                       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:427)
                                                       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:367)
                                                       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:332)
                                                       at com.facebook.yoga.YogaConfig.<clinit>(YogaConfig.java:19)
                                                       at com.facebook.litho.ComponentsPools.acquireInternalNode(ComponentsPools.java:194)
                                                       at com.facebook.litho.ComponentContext.newLayoutBuilder(ComponentContext.java:286)
                                                       at com.facebook.litho.Column.create(Column.java:24)
                                                       at com.facebook.litho.Column.create(Column.java:28)
                                                       at com.facebook.litho.ComponentLifecycle.onCreateLayout(ComponentLifecycle.java:352)
                                                       at com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:238)
                                                       at com.facebook.litho.ComponentContext.newLayoutBuilder(ComponentContext.java:297)
                                                       at com.facebook.litho.Layout.create(Layout.java:40)
                                                       at com.facebook.litho.Component$Builder.withLayout(Component.java:526)
                                                       at com.facebook.litho.sections.widget.RecyclerCollectionComponentSpec.onCreateLayout(RecyclerCollectionComponentSpec.java:213)
                                                       at com.facebook.litho.sections.widget.RecyclerCollectionComponent.onCreateLayout(RecyclerCollectionComponent.java:100)
                                                       at com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:238)
                                                       at com.facebook.litho.ComponentContext.newLayoutBuilder(ComponentContext.java:297)
                                                       at com.facebook.litho.Layout.create(Layout.java:40)
                                                       at com.facebook.litho.Component$Builder.withLayout(Component.java:526)
                                                       at com.facebook.litho.Component$Builder.buildWithLayout(Component.java:511)
                                                       at com.facebook.samples.litho.DemoListComponentSpec.onCreateLayout(DemoListComponentSpec.java:50)
                                                       at com.facebook.samples.litho.DemoListComponent.onCreateLayout(DemoListComponent.java:42)
                                                       at com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:238)
                                                       at com.facebook.litho.LayoutState.createTree(LayoutState.java:1385)
                                                       at com.facebook.litho.LayoutState.createAndMeasureTreeForComponent(LayoutState.java:1561)
                                                       at com.facebook.litho.LayoutState.calculate(LayoutState.java:1063)
                                                       at com.facebook.litho.ComponentTree.calculateLayoutState(ComponentTree.java:1489)
                                                       at com.facebook.litho.ComponentTree.measure(ComponentTree.java:655)
                                                       at com.facebook.litho.LithoView.onMeasure(LithoView.java:265)
                                                       at android.view.View.measure(View.java:17585)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5543)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                       at android.view.View.measure(View.java:17585)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5543)
                                                       at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:400)
                                                       at android.view.View.measure(View.java:17585)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5543)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                       at android.view.View.measure(View.java:17585)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5543)
                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                   	at android.view.View.measure(Vie

**Comment by passy** [comment]
Please use the template when creating new issues so we can help you. Without code to reproduce and more information, we can't support you.
