### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Inconsistency detected.

### ISSUE THREAD

**Issue by ar-g** [facebook/litho#317]
Quire nasty exception, happens rarely and randomly

` java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0(offset:-1).state:9 com.facebook.litho.widget.LithoRecylerView{4300bed8 VFED.... ......ID 0,0-800,1280}, adapter:com.facebook.litho.widget.RecyclerBinder$InternalAdapter@42870d80, layout:com.facebook.litho.widget.StaggeredGridLayoutInfo$LithoStaggeredGridLayoutManager@4286fec8, context:com.facebook.litho.ComponentContext@42a64c28
                                                                at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5654)
                                                                at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                                                                at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
                                                                at android.support.v7.widget.LayoutState.next(LayoutState.java:100)
                                                                at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1570)
                                                                at android.support.v7.widget.StaggeredGridLayoutManager.scrollBy(StaggeredGridLayoutManager.java:2142)
                                                                at android.support.v7.widget.StaggeredGridLayoutManager.fixEndGap(StaggeredGridLayoutManager.java:1381)
                                                                at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:697)
                                                                at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:604)
                                                                at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3670)
                                                                at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3434)
                                                                at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
                                                                at android.view.View.layout(View.java:15594)`

**Comment by passy** [comment]
Do you have any demo code or steps to reproduce?

**Comment by ar-g** [comment]
Not related to litho
