### ISSUE TITLE
Component.makeShallowCopy() : java.lang.NullPointerException

### ISSUE THREAD

**Issue by sharkcodev** [facebook/litho#352]
- [X] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
```
    lithoVersion = '0.6.1'

    // Litho
    implementation "com.facebook.litho:litho-core:${lithoVersion}"
    implementation "com.facebook.litho:litho-widget:${lithoVersion}"
    compileOnly "com.facebook.litho:litho-annotations:${lithoVersion}"
    kapt "com.facebook.litho:litho-processor:${lithoVersion}"
    implementation 'com.facebook.soloader:soloader:0.2.0'
```

## Issues and Steps to Reproduce
Happening once you open the app, only happening in some devices but not of the same brand.

## Expected Behavior
Display litho view and its content.

## Link to Code
Stacktrace:

```
Fatal Exception: java.lang.NullPointerException
       at com.facebook.litho.ComponentTree.measure(ComponentTree.java:583)
       at com.facebook.litho.LithoView.onMeasure(LithoView.java:210)
       at android.view.View.measure(View.java:16749)
       at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:8791)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1584)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3670)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3434)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:611)
       at com.facebook.litho.widget.RecyclerViewWrapper.onLayout(RecyclerViewWrapper.java:106)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at com.facebook.litho.MountState.applyBoundsToMountContent(MountState.java:1097)
       at com.facebook.litho.MountState.updateBoundsForMountedLayoutOutput(MountState.java:770)
       at com.facebook.litho.MountState.updateMountItemIfNeeded(MountState.java:629)
       at com.facebook.litho.MountState.mount(MountState.java:225)
       at com.facebook.litho.LithoView.mount(LithoView.java:562)
       at com.facebook.litho.ComponentTree.mountComponent(ComponentTree.java:476)
       at com.facebook.litho.ComponentTree.incrementalMountComponent(ComponentTree.java:428)
       at com.facebook.litho.ComponentTree.mountComponentIfDirty(ComponentTree.java:404)
       at com.facebook.litho.ComponentTree.layout(ComponentTree.java:662)
       at com.facebook.litho.LithoView.performLayout(LithoView.java:230)
       at com.facebook.litho.ComponentHost.onLayout(ComponentHost.java:734)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:13171)
       at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:875)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1692)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1534)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1443)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1692)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1534)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1443)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1172)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1692)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1534)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1443)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15033)
       at android.view.ViewGroup.layout(ViewGroup.java:4799)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2143)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1854)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1062)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5996)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5590)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by pavlospt** [comment]
hey @sharkcodev, have you tried it with version 0.14.0 as well? Would you be able to give it a try?

**Comment by passy** [comment]
Yes, please try this with a newer version and if it persists open a new issue. `0.6.1` is *really old* and difficult for us to triage. Thanks for the report!

**Comment by sharkcodev** [comment]
Thanks, I will try with a newer version, if I am still having this issue will open the ticket again as suggested.
