### ISSUE TITLE
Getting IndexArrayOutOFBound in RecyclerBinder

### ISSUE THREAD

**Issue by mishrabhilash** [facebook/litho#389]
Caused by java.lang.IndexOutOfBoundsException: Index: 46, Size: 46
       at java.util.ArrayList.get(ArrayList.java:411)
       at com.facebook.litho.widget.RecyclerBinder.updateRangeAt(RecyclerBinder.java:968)
       at com.facebook.litho.sections.widget.SectionBinderTarget.updateRange(SectionBinderTarget.java:127)
       at com.facebook.litho.sections.BatchedTarget.dispatchLastEvent(BatchedTarget.java:228)
       at com.facebook.litho.sections.BatchedTarget.insert(BatchedTarget.java:65)
       at com.facebook.litho.sections.SectionTree.postChangesetsToHandler(SectionTree.java:1068)
       at com.facebook.litho.sections.SectionTree.access$2700(SectionTree.java:70)
       at com.facebook.litho.sections.SectionTree$SectionsMainThreadHandler.handleMessage(SectionTree.java:1310)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6377)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

Not able to reproduce, but getting report of this crash from production devices. Any ideas what could be going wrong?

**Comment by mihaelao** [comment]
Hey @mishrabhilash, this is usually the result of a thread safety issue that can occur if your data structures are not immutable. The first thing I'd do is try to debug the operations that are performed on the items in your list by enabling sections debugging here: https://github.com/facebook/litho/blob/66d10f00bc41107656e41810cc6b15e7ebabdef1/litho-widget/src/main/java/com/facebook/litho/widget/SectionsDebug.java#L25

**Comment by mishrabhilash** [comment]
Thanks @mihaelao. Immutability was the issue indeed.
