### ISSUE TITLE
a11y onPopulateAccessibilityEventHandler crash

### ISSUE THREAD

**Issue by anushreeag** [facebook/litho#434]
- [ Yes ] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
    implementation 'com.facebook.litho:litho-core:0.15.0'
    implementation 'com.facebook.litho:litho-widget:0.15.0'
    compileOnly 'com.facebook.litho:litho-annotations:0.15.0'
    annotationProcessor 'com.facebook.litho:litho-processor:0.15.0'

## Issues and Steps to Reproduce
App crashes with a Null pointer exception : mHasEventDispatcher is null
I am trying to use accessibility on text component using Litho.
I have tried a sample application which has only text and added a onPopulateAccessibilityEvent in my Layout Spec class as mentioned in Litho accessibility document.
The application crashes only when Talkback is on.

## Expected Behavior
Talkback should work as expected and output of talkback should have "Hi , I am TextView"
Please let me know if anything is wrong.

## Link to Code
MainActivity.java
```
public class MainActivity extends AppCompatActivity {

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    LithoView view = new LithoView(this);
    ComponentContext context = view.getComponentContext();
    Component component = MyComponent.create(context).onPopulateAccessibilityEventHandler(MyComponent.onPopulateAccessibilityEvent(context)).build();
    setContentView(view.create(context,component));
  }
}
```

MyComponentSpec.java
```
@LayoutSpec
public class MyComponentSpec {
  @OnCreateLayout
  static Component onCreateLayout(ComponentContext c) {
    return Text.create(c).text("Hi").textSizeDip(30).build();
  }

  @OnEvent(OnPopulateAccessibilityEventEvent.class)
  static void onPopulateAccessibilityEvent(
      ComponentContext c,
      @FromEvent View host,
      @FromEvent AccessibilityEvent event,
      @FromEvent AccessibilityDelegateCompat superDelegate) {
    superDelegate.onPopulateAccessibilityEvent(host, event);
    event.getText().add("Hi , I am TextView");
  }
}
```

**Comment by anushreeag** [comment]
Crash Logs : 

    --------- beginning of crash
2018-10-01 11:44:21.436 8105-8105/com.example.lithoexample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.lithoexample, PID: 8105
    java.lang.NullPointerException: Attempt to invoke interface method 'com.facebook.litho.EventDispatcher com.facebook.litho.HasEventDispatcher.getEventDispatcher()' on a null object reference
        at com.facebook.litho.EventDispatcherUtils.dispatchOnPopulateAccessibilityEvent(EventDispatcherUtils.java:301)
        at com.facebook.litho.ComponentAccessibilityDelegate.onPopulateAccessibilityEvent(ComponentAccessibilityDelegate.java:281)
        at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateApi16Impl$1.onPopulateAccessibilityEvent(AccessibilityDelegateCompat.java:132)
        at android.view.View.onPopulateAccessibilityEvent(View.java:6446)
        at android.view.View.dispatchPopulateAccessibilityEventInternal(View.java:6408)
        at android.view.ViewGroup.dispatchPopulateAccessibilityEventInternal(ViewGroup.java:2950)
        at android.view.View$AccessibilityDelegate.dispatchPopulateAccessibilityEvent(View.java:23510)
        at android.support.v4.view.AccessibilityDelegateCompat.dispatchPopulateAccessibilityEvent(AccessibilityDelegateCompat.java:269)
        at com.facebook.litho.ComponentAccessibilityDelegate.dispatchPopulateAccessibilityEvent(ComponentAccessibilityDelegate.java:275)
        at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateApi16Impl$1.dispatchPopulateAccessibilityEvent(AccessibilityDelegateCompat.java:115)
        at android.view.View.dispatchPopulateAccessibilityEvent(View.java:6394)
        at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:6361)
        at android.view.View$AccessibilityDelegate.sendAccessibilityEventUnchecked(View.java:23489)
        at android.support.v4.view.AccessibilityDelegateCompat.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:248)
        at com.facebook.litho.ComponentAccessibilityDelegate.sendAccessibilityEventUnchecked(ComponentAccessibilityDelegate.java:261)
        at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateApi16Impl$1.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:148)
        at android.view.View.sendAccessibilityEventUnchecked(View.java:6341)
        at android.view.View.sendAccessibilityEventInternal(View.java:6320)
        at android.view.View$AccessibilityDelegate.sendAccessibilityEvent(View.java:23447)
        at android.support.v4.view.AccessibilityDelegateCompat.sendAccessibilityEvent(AccessibilityDelegateCompat.java:226)
        at com.facebook.litho.ComponentAccessibilityDelegate.sendAccessibilityEvent(ComponentAccessibilityDelegate.java:248)
        at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateApi16Impl$1.sendAccessibilityEvent(AccessibilityDelegateCompat.java:143)
        at android.view.View.sendAccessibilityEvent(View.java:6285)
        at android.view.View.requestAccessibilityFocus(View.java:8956)
        at android.view.View.performAccessibilityActionInternal(View.java:9645)
        at android.view.View$AccessibilityDelegate.performAccessibilityAction(View.java:23467)
        at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateApi16Impl.performAccessibilityAction(AccessibilityDelegateCompat.java:179)
        at android.support.v4.view.AccessibilityDelegateCompat.performAccessibilityAction(AccessibilityDelegateCompat.java:391)
        at com.facebook.litho.ComponentAccessibilityDelegate.performAccessibilityAction(ComponentAccessibilityDelegate.java:319)
        at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateApi16Impl$1.performAccessibilityAction(AccessibilityDelegateCompat.java:161)
        at android.view.View.performAccessibilityAction(View.java:9578)
        at com.facebook.litho.ComponentHost.performAccessibilityAction(ComponentHost.java:1373)
        at android.support.v4.view.ViewCompat$ViewCompatApi16Impl.performAccessibilityAction(ViewCompat.java:1047)
        at android.support.v4.view.ViewCompat.performAccessibilityAction(ViewCompat.java:1994)
        at android.support.v4.widget.ExploreByTouchHelper.performActionForHost(ExploreByTouchHelper.java:901)
2018-10-01 11:44:21.436 8105-8105/com.example.lithoexample E/AndroidRuntime:     at android.support.v4.widget.ExploreByTouchHelper.performAction(ExploreByTouchHelper.java:894)
        at android.support.v4.widget.ExploreByTouchHelper$MyNodeProvider.performAction(ExploreByTouchHelper.java:1248)
        at android.support.v4.view.accessibility.AccessibilityNodeProviderCompat$AccessibilityNodeProviderKitKatImpl$1.performAction(AccessibilityNodeProviderCompat.java:107)
        at android.support.v4.view.accessibility.AccessibilityNodeProviderCompatKitKat$1.performAction(AccessibilityNodeProviderCompatKitKat.java:59)
        at android.view.AccessibilityInteractionController.performAccessibilityActionUiThread(AccessibilityInteractionController.java:664)
        at android.view.AccessibilityInteractionController.-wrap6(AccessibilityInteractionController.java)
        at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1201)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by anushreeag** [comment]
[a11yLithoCrash.txt](https://github.com/facebook/litho/files/2435210/a11yLithoCrash.txt)

**Comment by anushreeag** [comment]
Attaching the source code - Contains src folder, build.gradle file.
[a11yLithoExample.zip](https://github.com/facebook/litho/files/2435317/a11yLithoExample.zip)

**Comment by vinc3m1** [comment]
```
    --------- beginning of crash
2018-10-01 11:44:21.436 8105-8105/com.example.lithoexample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.lithoexample, PID: 8105
    java.lang.NullPointerException: Attempt to invoke interface method 'com.facebook.litho.EventDispatcher com.facebook.litho.HasEventDispatcher.getEventDispatcher()' on a null object reference
        at com.facebook.litho.EventDispatcherUtils.dispatchOnPopulateAccessibilityEvent(EventDispatcherUtils.java:301)
        at com.facebook.litho.ComponentAccessibilityDelegate.onPopulateAccessibilityEvent(ComponentAccessibilityDelegate.java:281)
        at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateApi16Impl$1.onPopulateAccessibilityEvent(AccessibilityDelegateCompat.java:132)
        at android.view.View.onPopulateAccessibilityEvent(View.java:6446)
        at android.view.View.dispatchPopulateAccessibilityEventInternal(View.java:6408)
        at android.view.ViewGroup.dispatchPopulateAccessibilityEventInternal(ViewGroup.java:2950)
        at android.view.View$AccessibilityDelegate.dispatchPopulateAccessibilityEvent(View.java:23510)
        at android.support.v4.view.AccessibilityDelegateCompat.dispatchPopulateAccessibilityEvent(AccessibilityDelegateCompat.java:269)
        at com.facebook.litho.ComponentAccessibilityDelegate.dispatchPopulateAccessibilityEvent(ComponentAccessibilityDelegate.java:275)
        at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateApi16Impl$1.dispatchPopulateAccessibilityEvent(AccessibilityDelegateCompat.java:115)
        at android.view.View.dispatchPopulateAccessibilityEvent(View.java:6394)
        at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:6361)
        at android.view.View$AccessibilityDelegate.sendAccessibilityEventUnchecked(View.java:23489)
        at android.support.v4.view.AccessibilityDelegateCompat.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:248)
        at com.facebook.litho.ComponentAccessibilityDelegate.sendAccessibilityEventUnchecked(ComponentAccessibilityDelegate.java:261)
        at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateApi16Impl$1.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:148)
        at android.view.View.sendAccessibilityEventUnchecked(View.java:6341)
        at android.view.View.sendAccessibilityEventInternal(View.java:6320)
        at android.view.View$AccessibilityDelegate.sendAccessibilityEvent(View.java:23447)
        at android.support.v4.view.AccessibilityDelegateCompat.sendAccessibilityEvent(AccessibilityDelegateCompat.java:226)
        at com.facebook.litho.ComponentAccessibilityDelegate.sendAccessibilityEvent(ComponentAccessibilityDelegate.java:248)
        at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateApi16Impl$1.sendAccessibilityEvent(AccessibilityDelegateCompat.java:143)
        at android.view.View.sendAccessibilityEvent(View.java:6285)
        at android.view.View.requestAccessibilityFocus(View.java:8956)
        at android.view.View.performAccessibilityActionInternal(View.java:9645)
        at android.view.View$AccessibilityDelegate.performAccessibilityAction(View.java:23467)
        at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateApi16Impl.performAccessibilityAction(AccessibilityDelegateCompat.java:179)
        at android.support.v4.view.AccessibilityDelegateCompat.performAccessibilityAction(AccessibilityDelegateCompat.java:391)
        at com.facebook.litho.ComponentAccessibilityDelegate.performAccessibilityAction(ComponentAccessibilityDelegate.java:319)
        at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateApi16Impl$1.performAccessibilityAction(AccessibilityDelegateCompat.java:161)
        at android.view.View.performAccessibilityAction(View.java:9578)
        at com.facebook.litho.ComponentHost.performAccessibilityAction(ComponentHost.java:1373)
        at android.support.v4.view.ViewCompat$ViewCompatApi16Impl.performAccessibilityAction(ViewCompat.java:1047)
        at android.support.v4.view.ViewCompat.performAccessibilityAction(ViewCompat.java:1994)
        at android.support.v4.widget.ExploreByTouchHelper.performActionForHost(ExploreByTouchHelper.java:901)
2018-10-01 11:44:21.436 8105-8105/com.example.lithoexample E/AndroidRuntime:     at android.support.v4.widget.ExploreByTouchHelper.performAction(ExploreByTouchHelper.java:894)
        at android.support.v4.widget.ExploreByTouchHelper$MyNodeProvider.performAction(ExploreByTouchHelper.java:1248)
        at android.support.v4.view.accessibility.AccessibilityNodeProviderCompat$AccessibilityNodeProviderKitKatImpl$1.performAction(AccessibilityNodeProviderCompat.java:107)
        at android.support.v4.view.accessibility.AccessibilityNodeProviderCompatKitKat$1.performAction(AccessibilityNodeProviderCompatKitKat.java:59)
        at android.view.AccessibilityInteractionController.performAccessibilityActionUiThread(AccessibilityInteractionController.java:664)
        at android.view.AccessibilityInteractionController.-wrap6(AccessibilityInteractionController.java)
        at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1201)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by vinc3m1** [comment]
oh this is because onPopulateAccessibilityEventHandler() has to be called from within a spec.

**Comment by anushreeag** [comment]
Calling from within a spec worked. Thanks.
