### ISSUE TITLE
Gradle Tests don't fail when asserts or crashes happen off main thread 

### ISSUE THREAD

**Issue by vinc3m1** [facebook/litho#458]
I'm trying to test #457 but running into a bunch of issues.
1. Robolectric's ShadowLooper.getMainLooper throws NPEs: https://github.com/robolectric/robolectric/issues/2876
2. assertions off the main thread don't actually fail tests
3. I tried `buck test ...` as well, but everything is failing there.

```
gw :litho-it:testDebugUnitTest --tests com.facebook.litho.ComponentTreeTest

> Task :yoga:buckBuild
Not using buckd because watchman isn't installed.
PARSING BUCK FILES... 0.0s (100%)
CREATING ACTION GRAPH: FINISHED IN 0.3s
DOWNLOADED 0 ARTIFACTS, 0.00 BYTES, 0.0% CACHE MISS
BUILDING: FINISHED IN 2.7s (100%) 1/1 JOBS, 0 UPDATED
BUILD SUCCEEDED

> Task :litho-it:testDebugUnitTest

com.facebook.litho.ComponentTreeTest > testSetSizeSpec PASSED

com.facebook.litho.ComponentTreeTest > testSetRootAndSizeSpecWithTreeProps PASSED

com.facebook.litho.ComponentTreeTest > testLayoutStateFutureMainWaitingOnBg PASSED

com.facebook.litho.ComponentTreeTest > testSetSizeSpecAsyncThenSyncAfterRunningTask STANDARD_ERROR
    Exception in thread "ComponentLayoutThread1-1" java.lang.NullPointerException
        at org.robolectric.shadows.ShadowLooper.getMainLooper(ShadowLooper.java:70)
        at android.os.Looper.getMainLooper(Looper.java)
        at com.facebook.litho.ThreadUtils.isMainThread(ThreadUtils.java:57)
        at com.facebook.litho.ComponentTree$LayoutStateFuture.runAndGet(ComponentTree.java:2149)
        at com.facebook.litho.ComponentTree.calculateLayoutState(ComponentTree.java:1985)
        at com.facebook.litho.ComponentTree.calculateLayout(ComponentTree.java:1642)
        at com.facebook.litho.ComponentTree.access$2800(ComponentTree.java:81)
        at com.facebook.litho.ComponentTree$CalculateLayoutRunnable.tracedRun(ComponentTree.java:2271)
        at com.facebook.litho.ThreadTracingRunnable.run(ThreadTracingRunnable.java:89)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at com.facebook.litho.LayoutThreadFactory$1.run(LayoutThreadFactory.java:55)
        at java.lang.Thread.run(Thread.java:748)
    Exception in thread "Thread-5" java.lang.NullPointerException
        at org.robolectric.shadows.ShadowLooper.getMainLooper(ShadowLooper.java:70)
        at android.os.Looper.getMainLooper(Looper.java)
        at com.facebook.litho.ThreadUtils.isMainThread(ThreadUtils.java:57)
        at com.facebook.litho.ComponentTree$LayoutStateFuture.runAndGet(ComponentTree.java:2149)
        at com.facebook.litho.ComponentTree.calculateLayoutState(ComponentTree.java:1985)
        at com.facebook.litho.ComponentTreeTest$3.run(ComponentTreeTest.java:685)
        at java.lang.Thread.run(Thread.java:748)

com.facebook.litho.ComponentTreeTest > testSetSizeSpecAsyncThenSyncAfterRunningTask PASSED

com.facebook.litho.ComponentTreeTest > testSetCompatibleSizeSpec PASSED

com.facebook.litho.ComponentTreeTest > testSetRootAfterRelease PASSED

com.facebook.litho.ComponentTreeTest > testSetSizeSpecAsync PASSED

com.facebook.litho.ComponentTreeTest > testCreateOneLayoutStateFuture STANDARD_ERROR
    Exception in thread "ComponentLayoutThread1-2" java.lang.NullPointerException
        at org.robolectric.shadows.ShadowSystemClock.now(ShadowSystemClock.java:25)
        at org.robolectric.shadows.ShadowSystemClock.uptimeMillis(ShadowSystemClock.java:54)
        at android.os.SystemClock.uptimeMillis(SystemClock.java)
        at android.os.Handler.sendMessageDelayed(Handler.java:446)
        at android.os.Handler.sendMessage(Handler.java:383)
        at android.os.Message.sendToTarget(Message.java:360)
        at com.facebook.litho.ComponentTree.postBackgroundLayoutStateUpdated(ComponentTree.java:1756)
        at com.facebook.litho.ComponentTree.calculateLayout(ComponentTree.java:1717)
        at com.facebook.litho.ComponentTree.access$2800(ComponentTree.java:81)
        at com.facebook.litho.ComponentTree$CalculateLayoutRunnable.tracedRun(ComponentTree.java:2271)
        at com.facebook.litho.ThreadTracingRunnable.run(ThreadTracingRunnable.java:89)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at com.facebook.litho.LayoutThreadFactory$1.run(LayoutThreadFactory.java:55)
        at java.lang.Thread.run(Thread.java:748)
    Exception in thread "ComponentLayoutThread1-3" java.lang.NullPointerException
        at org.robolectric.shadows.ShadowLooper.getMainLooper(ShadowLooper.java:70)
        at android.os.Looper.getMainLooper(Looper.java)
        at com.facebook.litho.ThreadUtils.isMainThread(ThreadUtils.java:57)
        at com.facebook.litho.ComponentTree$LayoutStateFuture.runAndGet(ComponentTree.java:2149)
        at com.facebook.litho.ComponentTreeTest$2.run(ComponentTreeTest.java:631)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at com.facebook.litho.LayoutThreadFactory$1.run(LayoutThreadFactory.java:55)
        at java.lang.Thread.run(Thread.java:748)

com.facebook.litho.ComponentTreeTest > testCreateOneLayoutStateFuture PASSED

com.facebook.litho.ComponentTreeTest > testRecalculateDifferentRoots STANDARD_ERROR
    Exception in thread "Thread-6" java.lang.NullPointerException
        at org.robolectric.shadows.ShadowLooper.getMainLooper(ShadowLooper.java:70)
        at android.os.Looper.getMainLooper(Looper.java)
        at com.facebook.litho.ThreadUtils.isMainThread(ThreadUtils.java:57)
        at com.facebook.litho.ComponentTree$LayoutStateFuture.runAndGet(ComponentTree.java:2149)
        at com.facebook.litho.ComponentTree.calculateLayoutState(ComponentTree.java:1985)

com.facebook.litho.ComponentTreeTest > testRecalculateDifferentRoots PASSED

com.facebook.litho.ComponentTreeTest STANDARD_ERROR
        at com.facebook.litho.ComponentTreeTest$4.run(ComponentTreeTest.java:760)
        at java.lang.Thread.run(Thread.java:748)
    Exception in thread "ComponentLayoutThread1-4" java.lang.NullPointerException
        at org.robolectric.shadows.ShadowLooper.getMainLooper(ShadowLooper.java:70)
        at android.os.Looper.getMainLooper(Looper.java)
        at com.facebook.litho.ThreadUtils.isMainThread(ThreadUtils.java:57)
        at com.facebook.litho.ComponentTree$LayoutStateFuture.runAndGet(ComponentTree.java:2149)
        at com.facebook.litho.ComponentTree.calculateLayoutState(ComponentTree.java:1985)
        at com.facebook.litho.ComponentTree.calculateLayout(ComponentTree.java:1642)
        at com.facebook.litho.ComponentTree.access$2800(ComponentTree.java:81)
        at com.facebook.litho.ComponentTree$CalculateLayoutRunnable.tracedRun(ComponentTree.java:2271)
        at com.facebook.litho.ThreadTracingRunnable.run(ThreadTracingRunnable.java:89)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

com.facebook.litho.ComponentTreeTest > testSetCompatibleSizeSpecWithDifferentRoot STANDARD_ERROR
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at com.facebook.litho.LayoutThreadFactory$1.run(LayoutThreadFactory.java:55)
        at java.lang.Thread.run(Thread.java:748)

com.facebook.litho.ComponentTreeTest > testSetCompatibleSizeSpecWithDifferentRoot PASSED

com.facebook.litho.ComponentTreeTest > testSetSizeSpecWithOutput PASSED

com.facebook.litho.ComponentTreeTest > testSetSizeSpecAsyncThenSyncBeforeRunningTask PASSED

com.facebook.litho.ComponentTreeTest > testSetSizeSpecWithOutputWhenAttachedToViewWithSameSpec PASSED

com.facebook.litho.ComponentTreeTest > testSetComponentFromView PASSED

com.facebook.litho.ComponentTreeTest > testComponentTreeReleaseClearsView PASSED

com.facebook.litho.ComponentTreeTest > testSetRootAsyncFollowedByMeasureDoesntComputeSyncLayout PASSED

com.facebook.litho.ComponentTreeTest > testCreate PASSED

com.facebook.litho.ComponentTreeTest > testSetSizeSpecWithOutputWhenAttachedToViewWithNewSpec PASSED

com.facebook.litho.ComponentTreeTest > testRootWrapperComponent PASSED

com.facebook.litho.ComponentTreeTest > testsetTreeToTwoViewsBothAttached PASSED

com.facebook.litho.ComponentTreeTest > testSettingNewViewToTree PASSED

com.facebook.litho.ComponentTreeTest > testSetRootAsyncFollowedByNonCompatibleMeasureComputesSyncLayout PASSED

com.facebook.litho.ComponentTreeTest > testSetInput PASSED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 17s
163 actionable tasks: 3 executed, 160 up-to-date
```

**Comment by passy** [comment]
Uggh, that's doubly bad. Frustratingly, we cannot update Robolectric. We're stuck with 3.0 for the foreseeable future. :/ Buck should behave just the same way, but out of curiosity, what are you seeing there?

I don't really know if there's a good workaround for these things ...

**Comment by IanChilds** [comment]
Closing as I don't think there's anything we can do here, feel free to reopen if that's wrong.
