### ISSUE TITLE
ProgressSpec.getStyledIndeterminateDrawable (ProgressSpec.java:140)

### ISSUE THREAD

**Issue by ZumaLuma** [facebook/litho#463]
- I have searched [ProgressSpec exception] https://github.com/facebook/litho/issues/207 and this is not a duplicate

## Version
```
// Litho
	def litho_version = '0.20.0'
	implementation "com.facebook.litho:litho-core:$litho_version"
	implementation "com.facebook.litho:litho-widget:$litho_version"
	compileOnly "com.facebook.litho:litho-annotations:$litho_version"
	kapt "com.facebook.litho:litho-processor:$litho_version"

	// For integration with Fresco
	implementation "com.facebook.litho:litho-fresco:$litho_version"

	// Sections
	implementation "com.facebook.litho:litho-sections-core:$litho_version"
	implementation "com.facebook.litho:litho-sections-widget:$litho_version"
	compileOnly "com.facebook.litho:litho-sections-annotations:$litho_version"
	kapt "com.facebook.litho:litho-sections-processor:$litho_version"
```
## Issues and Steps to Reproduce
I have LoaderSpec, which contains progressSpec. On some devices from time to time there is a error with it:
```
Fatal Exception: com.facebook.litho.ComponentLifecycle$CreateLayoutException
Loader

Caused by android.content.res.Resources$NotFoundException
Drawable android:drawable/progress_medium_material with resource ID #0x1080612

Caused by java.lang.NullPointerException
Attempt to write to field 'android.animation.AnimatorSet$Node 

android.animation.AnimatorSet$Node.mLatestParent' on a null object reference
```

Stacktrace:
```
com.facebook.litho.widget.ProgressSpec.getStyledIndeterminateDrawable (ProgressSpec.java:140)
com.facebook.litho.widget.ProgressSpec.onPrepare (ProgressSpec.java:74)
com.facebook.litho.widget.Progress.onPrepare (Progress.java:101)
com.facebook.litho.ComponentLifecycle.createLayout (ComponentLifecycle.java:385)
com.facebook.litho.ComponentContext.newLayoutBuilder (ComponentContext.java:335)
com.facebook.litho.Layout.create (Layout.java:47)
com.facebook.litho.Layout.create (Layout.java:58)
com.facebook.litho.InternalNode.child (InternalNode.java:840)
com.facebook.litho.Row.resolve (Row.java:117)
com.facebook.litho.ComponentContext.resolveLayout (ComponentContext.java:358)
com.facebook.litho.ComponentLifecycle.createLayout (ComponentLifecycle.java:333)
com.facebook.litho.LayoutState.createTree (LayoutState.java:1522)
com.facebook.litho.LayoutState.createAndMeasureTreeForComponent (LayoutState.java:1709)
com.facebook.litho.LayoutState.calculate (LayoutState.java:1328)
com.facebook.litho.ComponentTree.calculateLayoutStateInternal (ComponentTree.java:2077)
com.facebook.litho.ComponentTree.calculateLayoutState (ComponentTree.java:2025)
com.facebook.litho.ComponentTree.calculateLayout (ComponentTree.java:1662)
com.facebook.litho.ComponentTree.access$3000 (ComponentTree.java:81)
com.facebook.litho.ComponentTree$CalculateLayoutRunnable.tracedRun (ComponentTree.java:2313)
com.facebook.litho.ThreadTracingRunnable.run (ThreadTracingRunnable.java:89)
``` 

## Expected Behavior
Would work without crash)

## Link to Code
```
@LayoutSpec
object LoaderSpec {
	@OnCreateLayout
	fun onCreateLayout(c: ComponentContext): Component {
		return row(c) {
			justifyContent(YogaJustify.CENTER)
			paddingDip(YogaEdge.VERTICAL, 10f)

			child(c, Progress::create) {
				widthDip(20f)
				heightDip(20f)
			}
		}.build()
	}

	@OnEnteredRange(name = "prefetch")
	fun onEnteredWorkingRange(c: ComponentContext,
                                                          @Prop loadMore: () -> Unit) {
		loadMore()
	}

	@OnRegisterRanges
	fun registerWorkingRanges(c: ComponentContext) {
		Loader.registerPrefetchWorkingRange(c, object : WorkingRange {
			override fun shouldEnterRange(position: Int, firstVisibleIndex: Int, lastVisibleIndex: Int, firstFullyVisibleIndex: Int, lastFullyVisibleIndex: Int): Boolean {
				return position in firstVisibleIndex..lastVisibleIndex
	
	}

			override fun shouldExitRange(position: Int, firstVisibleIndex: Int, lastVisibleIndex: Int, firstFullyVisibleIndex: Int, lastFullyVisibleIndex: Int): Boolean {
				return position !in firstVisibleIndex..lastVisibleIndex
			}
		})
	}
}
```

**Comment by Tobyyyyyyyyyy** [comment]
Similar crash with me. 

I found a similar [issue](https://github.com/facebook/react-native/issues/7476) and provide a [solution](https://github.com/facebook/react-native/commit/b9396cd74419dd4165fb051605076d19b1c18905). Is this a situation?

Stacktrace: 

```
Caused by java.lang.NullPointerException: Null pointer exception during instruction 'invoke-static {v5}, android.animation.AnimatorSet$Node android.animation.AnimatorSet$Node.access$200(android.animation.AnimatorSet$Node) // method@891'
       at android.animation.AnimatorSet.clone(AnimatorSet.java:707)
       at android.animation.AnimatorSet.clone(AnimatorSet.java:50)
       at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState.(AnimatedVectorDrawable.java:363)
       at android.graphics.drawable.AnimatedVectorDrawable.mutate(AnimatedVectorDrawable.java:149)
       at android.content.res.Resources.loadDrawable(Resources.java:3844)
       at android.content.res.Resources.getDrawable(Resources.java:1949)
       at android.content.Context.getDrawable(Context.java:409)
       at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:358)
       at com.facebook.litho.widget.ProgressSpec.getStyledIndeterminateDrawable(ProgressSpec.java:141)
       at com.facebook.litho.widget.ProgressSpec.onPrepare(ProgressSpec.java:75)
       at com.facebook.litho.widget.Progress.onPrepare(Progress.java:104)
       at com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:391)
       at com.facebook.litho.ComponentContext.newLayoutBuilder(ComponentContext.java:344)
       at com.facebook.litho.Layout.create(Layout.java:47)
       at com.facebook.litho.Layout.create(Layout.java:58)
       at com.facebook.litho.InternalNode.child(InternalNode.java:745)
       at com.facebook.litho.Column.resolve(Column.java:114)
       at com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:330)
       at com.facebook.litho.LayoutState.createTree(LayoutState.java:1606)
       at com.facebook.litho.LayoutState.createAndMeasureTreeForComponent(LayoutState.java:1820)
       at com.facebook.litho.LayoutState.calculate(LayoutState.java:1407)
       at com.facebook.litho.ComponentTree.calculateLayoutStateInternal(ComponentTree.java:2118)
       at com.facebook.litho.ComponentTree.calculateLayoutState(ComponentTree.java:2082)
       at com.facebook.litho.ComponentTree.calculateLayout(ComponentTree.java:1706)
       at com.facebook.litho.ComponentTree.access$3500(ComponentTree.java:82)
       at com.facebook.litho.ComponentTree$CalculateLayoutRunnable.tracedRun(ComponentTree.java:2388)
       at com.facebook.litho.ThreadTracingRunnable.run(ThreadTracingRunnable.java:89)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```
