### ISSUE TITLE
Multi color Border crash on targetSDK 28

### ISSUE THREAD

**Issue by nuron142** [facebook/litho#519]
I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
 lithoVersion                 : "0.25.0",

## Issues and Steps to Reproduce
Using Border component with only one edge color.
```
.border(
      Border.create(componentContext)
           .widthRes(YogaEdge.ALL, R.dimen.dimen_1dp)
           .colorRes(YogaEdge.TOP, R.color.grey)
           .build()
)
```
The app crashes on Android 9 because of above code.
```
java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
        at android.graphics.Canvas.checkValidClipOp(Canvas.java:779)
        at android.graphics.Canvas.clipRect(Canvas.java:918)
        at com.facebook.litho.drawable.BorderColorDrawable.drawMultiColoredBorders(BorderColorDrawable.java:190)
        at com.facebook.litho.drawable.BorderColorDrawable.draw(BorderColorDrawable.java:124)
        at com.facebook.litho.MatrixDrawable.draw(MatrixDrawable.java:170)
        at com.facebook.litho.ComponentHost$InterleavedDispatchDraw.drawNext(ComponentHost.java:1462)
        at com.facebook.litho.ComponentHost$InterleavedDispatchDraw.access$400(ComponentHost.java:1411)
        at com.facebook.litho.ComponentHost.dispatchDraw(ComponentHost.java:770)
        at android.view.View.draw(View.java:20369)
        at com.facebook.litho.LithoView.draw(LithoView.java:669)
        at android.view.View.updateDisplayListIfDirty(View.java:19241)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4820)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at com.facebook.litho.widget.LithoRecylerView.dispatchDraw(LithoRecylerView.java:76)
        at android.view.View.draw(View.java:20369)
        at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4219)
        at android.view.View.updateDisplayListIfDirty(View.java:19241)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at android.view.View.draw(View.java:20369)
        at android.view.View.updateDisplayListIfDirty(View.java:19241)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at com.facebook.litho.ComponentHost.dispatchDraw(ComponentHost.java:763)
        at android.view.View.draw(View.java:20369)
        at com.facebook.litho.LithoView.draw(LithoView.java:669)
        at android.view.View.updateDisplayListIfDirty(View.java:19241)
        at android.view.View.draw(View.java:20094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)
        at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
        at android.view.View.draw(View.java:20369)
```

In  BorderColorDrawable class inside drawMultiColoredBorders, this method is being called:
` canvas.clipRect(width - hypotenuse, height - hypotenuse, width, height, Region.Op.UNION);` 

Using Region.Op.UNION is not allowed in Android 9 and this is causing the crash. 
```
Inside android.graphics.Canvas.java

private static void checkValidClipOp(@NonNull Region.Op op) {
        if (sCompatiblityVersion >= Build.VERSION_CODES.P
                && op != Region.Op.INTERSECT && op != Region.Op.DIFFERENCE) {
            throw new IllegalArgumentException(
                    "Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed");
        }
    }

```

**Comment by adityasharat** [comment]
Thank you for reporting, will take a look at this soon. It seems that all the `canvas.clipRect(width - hypotenuse, 0, width, hypotenuse, Region.Op.UNION);` need to have an alternative implementation for P.
