### ISSUE TITLE
Inconsistent behavior or wrong exception

### ISSUE THREAD

**Issue by ChristinaGit** [facebook/litho#623]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
`Android v6.0.1`

```groovy
    implementation 'com.facebook.litho:litho-core:0.33.0'
    implementation 'com.facebook.litho:litho-widget:0.33.0'

    kapt 'com.facebook.litho:litho-processor:0.33.0'
    implementation 'com.facebook.soloader:soloader:0.6.0'
    implementation 'com.facebook.litho:litho-fresco:0.33.0'

    implementation 'com.facebook.litho:litho-sections-core:0.33.0'
    implementation 'com.facebook.litho:litho-sections-widget:0.33.0'
    compileOnly 'com.facebook.litho:litho-sections-annotations:0.33.0'
    kapt 'com.facebook.litho:litho-sections-processor:0.33.0'
```

## Issues and Steps to Reproduce
```kotlin
@LayoutSpec
object TestTextInputHandleSpec {
    @OnCreateLayout
    fun onCreateLayout(
        c: ComponentContext
    ): Component {
        val handle = Handle()

        return Column.create(c)
            .paddingDip(YogaEdge.ALL, 16f)
            .clickHandler(TestTextInputHandle.onClick(c, handle))
            .child(
                Text.create(c)
                    .text("HHHHHHHHHHHHHH")
                    .textSizeSp(40f)
            )
            .child(
                TextInput.create(c)
                    .handle(handle)
                    .textSizeSp(22f)
                    .textChangedEventHandler(TestTextInputHandle.onTextChanged(c))
            )
            .build()
    }

    @OnEvent(ClickEvent::class)
    fun onClick(
        c: ComponentContext,
        @Param handle: Handle
    ) {
        TextInput.setText(c, handle, "")
    }

    @OnEvent(TextChangedEvent::class)
    fun onTextChanged(c: ComponentContext, @FromEvent text: String) {
    }
}

setContentView(LithoView.create(c, TestTextInputHandle.create(ComponentContext(this)).build()))
```
An exception occurs when you click on `TextView` 
<pre>
 java.lang.ClassCastException: com.facebook.litho.widget.SetTextEvent cannot be cast to com.facebook.litho.widget.SetSelectionEvent
        at com.facebook.litho.widget.TextInput.acceptTriggerEvent(TextInput.java:1184)
        at com.facebook.litho.EventTrigger.dispatchOnTrigger(EventTrigger.java:59)
        at com.facebook.litho.widget.TextInput.setText(TextInput.java:1037)
        at org.template.app.test.TestTextInputHandleSpec.onClick(TemplateActivity.kt:48)
        at org.template.app.test.TestTextInputHandle.onClick(TestTextInputHandle.java:31)
        at org.template.app.test.TestTextInputHandle.dispatchOnEvent(TestTextInputHandle.java:62)
        at com.facebook.litho.EventDispatcherUtils.dispatchOnClick(EventDispatcherUtils.java:65)
        at com.facebook.litho.ComponentClickListener.onClick(ComponentClickListener.java:31)
        at android.view.View.performClick(View.java:5482)
        at android.view.View$PerformClick.run(View.java:21646)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5444)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:727)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:617)
</pre>

## Expected Behavior
Should work as a version with a key (no errors)
```kotlin
@LayoutSpec
object TestTextInputKeySpec {
    @OnCreateLayout
    fun onCreateLayout(
        c: ComponentContext
    ): Component {
        val key = "input"

        return Column.create(c)
            .paddingDip(YogaEdge.ALL, 16f)
            .clickHandler(TestTextInputKey.onClick(c, key))
            .child(
                Text.create(c)
                    .text("HHHHHHHHHHHHHH")
                    .textSizeSp(40f)
            )
            .child(
                TextInput.create(c)
                    .key(key)
                    .textSizeSp(22f)
                    .textChangedEventHandler(TestTextInputKey.onTextChanged(c))
            )
            .build()
    }

    @OnEvent(ClickEvent::class)
    fun onClick(
        c: ComponentContext,
        @Param key: String
    ) {
        TextInput.setText(c, key, "")
    }

    @OnEvent(TextChangedEvent::class)
    fun onTextChanged(c: ComponentContext, @FromEvent text: String) {
    }
}
```
or throw out a more understandable error.

**Comment by colriot** [comment]
Hi @ChristinaGit ! Thanks for reporting it, we'll check it out

**Comment by andrewpmsmith** [comment]
Hi @ChristinaGit, it looks like the version of Litho you're using is too old. Handles for triggering events was very recently added. Despite being included in the release notes for v33, there were some issues with it that were fixed in the next version. Could you try upgrading?

**Comment by ChristinaGit** [comment]
Works in version 0.34.
