### ISSUE TITLE
couldn't find DSO to load: libyoga.so caused by: couldn't find DSO to load: libfb.so caused by:.........

### ISSUE THREAD

**Issue by EngDjango** [facebook/litho#711]
- [ ] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
litho: 0.37.1
soloader: 0.9.0

## Issues and Steps to Reproduce
the app crashes at startup only if I download it from the play store, 
but if I build a release apk no a bundle then the app is working fine!

## stacktrace
```
msg: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libyoga.so caused by: couldn't find DSO to load: libfb.so caused by: Didn't find class "com.facebook.jni.HybridData$Destructor" on path: DexPathList[[zip file "/data/app/com.*******-*****************==/base.apk", zip file "/data/app/com.**************-*****************==/split_config.arm64_v8a.apk", zip file "/data/app/com.***********-*************==/split_config.en.apk", zip file "/data/app/com.********-*******************==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.*********-***************==/lib/arm64, /data/app/com.********-*******************==/base.apk!/lib/arm64-v8a, /data/app/com.********-*******************==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/com.********-*******************==/split_config.en.apk!/lib/arm64-v8a, /data/app/com.********-*******************==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64]] result: 0 result: 0
stacktrace: com.facebook.litho.a0: RecyclerCollectionComponent
Caused by: com.facebook.litho.a0: Column
Caused by: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libyoga.so caused by: couldn't find DSO to load: libfb.so caused by: Didn't find class "com.facebook.jni.HybridData$Destructor" on path: DexPathList[[zip file "/data/app/com.********-*******************==/base.apk", zip file "/data/app/com.********-*******************==/split_config.arm64_v8a.apk", zip file "/data/app/com.********-*******************==/split_config.en.apk", zip file "/data/app/com.********-*******************==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.********-*******************==/lib/arm64, /data/app/com.********-*******************==/base.apk!/lib/arm64-v8a, /data/app/com.********-*******************==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/com.********-*******************==/split_config.en.apk!/lib/arm64-v8a, /data/app/com.********-*******************==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64]] result: 0 result: 0
	at com.facebook.j0.l.c(Unknown Source:343)
	at com.facebook.j0.l.o(Unknown Source:104)
	at com.facebook.j0.l.n(Unknown Source:2)
	at com.facebook.j0.l.l(Unknown Source:106)
	at com.facebook.j0.l.k(Unknown Source:1)
	at com.facebook.yoga.YogaNative.<clinit>(Unknown Source:2)
	at com.facebook.yoga.YogaNative.jni_YGConfigNew(Native Method)
	at com.facebook.yoga.a.<init>(Unknown Source:3)
	at com.facebook.yoga.b.a(Unknown Source:2)
	at com.facebook.litho.d6.a.a(Unknown Source:0)
	at com.facebook.litho.o3.<clinit>(Unknown Source:0)
	at com.facebook.litho.n2.a(Unknown Source:0)
	at com.facebook.litho.h.J1(Unknown Source:0)
	at com.facebook.litho.p2.g(Unknown Source:83)
	at com.facebook.litho.p2.f(Unknown Source:1)
	at com.facebook.litho.p2.g(Unknown Source:126)
	at com.facebook.litho.p2.f(Unknown Source:1)
	at com.facebook.litho.p2.i(Unknown Source:23)
	at com.facebook.litho.s2.z(Unknown Source:286)
	at com.facebook.litho.ComponentTree$e.d(Unknown Source:111)
	at com.facebook.litho.ComponentTree$e.c(Unknown Source:0)
	at com.facebook.litho.ComponentTree$e$a.a(Unknown Source:17)
	at com.facebook.litho.ComponentTree$e$a.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.facebook.litho.ComponentTree$e.m(Unknown Source:15)
	at com.facebook.litho.ComponentTree.y(Unknown Source:82)
	at com.facebook.litho.ComponentTree.x(Unknown Source:96)
	at com.facebook.litho.ComponentTree.P0(Unknown Source:287)
	at com.facebook.litho.ComponentTree.T0(Unknown Source:13)
	at com.facebook.litho.ComponentTree.y0(Unknown Source:104)
	at com.facebook.litho.LithoView.onMeasure(Unknown Source:177)
	at android.view.View.measure(View.java:23233)
	at androidx.constraintlayout.widget.ConstraintLayout$c.b(Unknown Source:405)
	at e.c.b.k.m.b.a(Unknown Source:114)
	at e.c.b.k.m.b.b(Unknown Source:72)
	at e.c.b.k.m.b.d(Unknown Source:284)
	at e.c.b.k.f.Y0(Unknown Source:23)
	at androidx.constraintlayout.widget.ConstraintLayout.o(Unknown Source:135)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(Unknown Source:31)
	at android.view.View.measure(View.java:23233)
	at androidx.viewpager.widget.ViewPager.onMeasure(Unknown Source:234)
	at android.view.View.measure(View.java:23233)
	at androidx.constraintlayout.widget.ConstraintLayout$c.b(Unknown Source:405)
	at e.c.b.k.m.b.a(Unknown Source:114)
	at e.c.b.k.m.b.d(Unknown Source:594)
	at e.c.b.k.f.Y0(Unknown Source:23)
	at androidx.constraintlayout.widget.ConstraintLayout.o(Unknown Source:135)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(Unknown Source:31)
	at android.view.View.measure(View.java:23233)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6748)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23233)
	at androidx.constraintlayout.widget.ConstraintLayout$c.b(Unknown Source:405)
	at e.c.b.k.m.b.a(Unknown Source:114)
	at e.c.b.k.m.b.d(Unknown Source:594)
	at e.c.b.k.f.Y0(Unknown Source:23)
	at androidx.constraintlayout.widget.ConstraintLayout.o(Unknown Source:135)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(Unknown Source:31)
	at android.view.View.measure(View.java:23233)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6748)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:154)
	at android.view.View.measure(View.java:23233)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6748)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23233)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6748)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23233)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6748)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23233)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6748)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:729)
	at android.view.View.measure(View.java:23233)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2769)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1619)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1902)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1507)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7431)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1019)
	at android.view.Choreographer.doCallbacks(Choreographer.java:830)
	at android.view.Choreographer.doFrame(Choreographer.java:765)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1005)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6698)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
```

**Comment by ironmanTony** [comment]
maybe downgrade soloader to 0.8.0 can resolve your problem

**Comment by zibellon** [comment]
Hello! I have the same problem...
I fix it to downgrade GRADLE to 3.2.1
When I up it to 4.x.x - catch crash? when publish app in PlayMarket

**Comment by zibellon** [comment]
Hello. I found how to fix it
3 steps
1. Up minSdk to 23
2. In gradle.properties add line:
android.bundle.enableUncompressedNativeLibs=false;
3. In your manifest file add line: 
android:extractNativeLibs=«true»;
